apiVersion: tekton.dev/v1
kind: Task
metadata:
    name: fetch-tgz-content-oci
spec:
    params:
        - description: location of the input
          name: url
          type: string
    results:
        - name: message
          type: string
    stepTemplate:
        computeResources: {}
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
                type: RuntimeDefault
    steps:
        - computeResources: {}
          image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:c76ee2db3a37efe5c530e9717b08547e90ba1054329e19690763a2d530ccfb4b
          name: fetch
          script: |
            #!/bin/bash

            set -euo pipefail
            set +x

            DIR=$(mktemp -d)

            imgpkg pull -i $(params.url) -o $DIR
            if [ $? -ne 0 ]; then
              printf "download failed" | tee $(results.message.path)
              exit 1
            fi

            shopt -s dotglob
            cp -R $DIR/* $(workspaces.store.path)
            shopt -u dotglob

            if [ $? -ne 0 ]; then
              printf "copy failed" | tee $(results.message.path)
              exit 1
            fi
    workspaces:
        - description: The store for the content
          name: store
