apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterSupplyChain/source-test-scan-to-url;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"ClusterSupplyChain","metadata":{"labels":{"kapp.k14s.io/app":"1718246236317745626","kapp.k14s.io/association":"v1.8c64ddca205b2ba4c71428ca92333680"},"name":"source-test-scan-to-url"},"spec":{"params":[{"default":"","name":"ca_cert_data"},{"name":"maven_repository_url","value":"https://repo.maven.apache.org/maven2"},{"default":"main","name":"gitops_branch"},{"default":"supplychain","name":"gitops_user_name"},{"default":"supplychain","name":"gitops_user_email"},{"default":"supplychain@cluster.local","name":"gitops_commit_message"},{"default":"git","name":"gitops_ssh_secret"},{"default":"https://github.com/","name":"gitops_server_address"},{"default":"davlloyd","name":"gitops_repository_owner"},{"default":"tap-gitops-home-1","name":"gitops_repository_name"},{"default":"github","name":"gitops_server_kind"},{"default":"","name":"gitops_commit_branch"},{"default":"ready
      for review","name":"gitops_pull_request_title"},{"default":"generated by supply
      chain","name":"gitops_pull_request_body"},{"name":"image_scanning_service_account_publisher","value":"default"},{"default":"default","name":"image_scanning_service_account_scanner"},{"default":"4Gi","name":"image_scanning_workspace_size"},{"name":"image_scanning_active_keychains","value":[]},{"name":"image_scanning_workspace_bindings","value":[]},{"name":"image_scanning_steps_env_vars","value":[]}],"resources":[{"name":"source-provider","params":[{"default":"default","name":"serviceAccount"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"source-template"}},{"name":"source-tester","sources":[{"name":"source","resource":"source-provider"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"testing-pipeline"}},{"name":"image-provider","params":[{"default":"default","name":"serviceAccount"},{"name":"registry","value":{"ca_cert_data":"","repository":"tap/supply-chain","server":"harbor.home.tanzu.rocks"}},{"default":"default","name":"clusterBuilder"},{"default":"./Dockerfile","name":"dockerfile"},{"default":"./","name":"docker_build_context"},{"default":[],"name":"docker_build_extra_args"}],"sources":[{"name":"source","resource":"source-tester"}],"templateRef":{"kind":"ClusterImageTemplate","options":[{"name":"kpack-template","selector":{"matchFields":[{"key":"spec.params[?(@.name==\"dockerfile\")]","operator":"DoesNotExist"}]}},{"name":"kaniko-template","selector":{"matchFields":[{"key":"spec.params[?(@.name==\"dockerfile\")]","operator":"Exists"}]}}]}},{"images":[{"name":"image","resource":"image-provider"}],"name":"image-scanner","params":[{"default":"scan-policy","name":"scanning_image_policy"},{"default":"private-image-scan-template","name":"scanning_image_template"},{"name":"registry","value":{"ca_cert_data":"","repository":"tap/supply-chain","server":"harbor.home.tanzu.rocks"}}],"templateRef":{"kind":"ClusterImageTemplate","name":"image-scanner-template"}},{"images":[{"name":"image","resource":"image-scanner"}],"name":"config-provider","params":[{"default":"default","name":"serviceAccount"}],"templateRef":{"kind":"ClusterConfigTemplate","name":"convention-template"}},{"configs":[{"name":"config","resource":"config-provider"}],"name":"app-config","templateRef":{"kind":"ClusterConfigTemplate","options":[{"name":"config-template","selector":{"matchLabels":{"apps.tanzu.vmware.com/workload-type":"web"}}},{"name":"server-template","selector":{"matchLabels":{"apps.tanzu.vmware.com/workload-type":"server"}}},{"name":"worker-template","selector":{"matchLabels":{"apps.tanzu.vmware.com/workload-type":"worker"}}}]}},{"configs":[{"name":"app_def","resource":"app-config"}],"name":"service-bindings","templateRef":{"kind":"ClusterConfigTemplate","name":"service-bindings"}},{"configs":[{"name":"app_def","resource":"service-bindings"}],"name":"api-descriptors","templateRef":{"kind":"ClusterConfigTemplate","name":"api-descriptors"}},{"configs":[{"name":"config","resource":"api-descriptors"}],"name":"config-writer","params":[{"default":"default","name":"serviceAccount"},{"name":"registry","value":{"ca_cert_data":"","repository":"tap/supply-chain","server":"harbor.home.tanzu.rocks"}}],"templateRef":{"kind":"ClusterTemplate","name":"config-writer-template"}},{"name":"deliverable","params":[{"name":"registry","value":{"ca_cert_data":"","repository":"tap/supply-chain","server":"harbor.home.tanzu.rocks"}}],"templateRef":{"kind":"ClusterTemplate","name":"deliverable-template"}}],"selector":{"apps.tanzu.vmware.com/has-tests":"true"},"selectorMatchExpressions":[{"key":"apps.tanzu.vmware.com/workload-type","operator":"In","values":["web","server","worker"]}]}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
  creationTimestamp: "2024-06-13T02:37:16Z"
  generation: 2
  labels:
    kapp.k14s.io/app: "1718246236317745626"
    kapp.k14s.io/association: v1.8c64ddca205b2ba4c71428ca92333680
  name: source-to-url-scan-test
  resourceVersion: "145245"
  uid: 663d5405-7908-4cfe-aafe-3b44e7cd5d45
spec:
  params:
  - default: ""
    name: ca_cert_data
  - name: maven_repository_url
    value: https://repo.maven.apache.org/maven2
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: git
    name: gitops_ssh_secret
  - default: https://github.com/
    name: gitops_server_address
  - default: davlloyd
    name: gitops_repository_owner
  - default: tap-gitops-home-1
    name: gitops_repository_name
  - default: github
    name: gitops_server_kind
  - default: ""
    name: gitops_commit_branch
  - default: ready for review
    name: gitops_pull_request_title
  - default: generated by supply chain
    name: gitops_pull_request_body
  - name: image_scanning_service_account_publisher
    value: default
  - default: default
    name: image_scanning_service_account_scanner
  - default: 4Gi
    name: image_scanning_workspace_size
  - name: image_scanning_active_keychains
    value: []
  - name: image_scanning_workspace_bindings
    value: []
  - name: image_scanning_steps_env_vars
    value: []
  resources:
  - name: source-provider
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: source-tester
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: testing-pipeline
  - name: source-scanner
    params:
    - default: scan-policy
      name: scanning_source_policy
    - default: blob-source-scan-template
      name: scanning_source_template
    sources:
    - name: source
      resource: source-tester
    templateRef:
      kind: ClusterSourceTemplate
      name: source-scanner-template
  - name: image-provider
    params:
    - default: default
      name: serviceAccount
    - name: registry
      value:
        ca_cert_data: ""
        repository: tap/supply-chain
        server: harbor.home.tanzu.rocks
    - default: default
      name: clusterBuilder
    - default: ./Dockerfile
      name: dockerfile
    - default: ./
      name: docker_build_context
    - default: []
      name: docker_build_extra_args
    sources:
    - name: source
      resource: source-scanner
    templateRef:
      kind: ClusterImageTemplate
      options:
      - name: kpack-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: DoesNotExist
      - name: kaniko-template
        selector:
          matchFields:
          - key: spec.params[?(@.name=="dockerfile")]
            operator: Exists
  - images:
    - name: image
      resource: image-provider
    name: image-scanner
    params:
    - default: scan-policy
      name: scanning_image_policy
    - default: private-image-scan-template
      name: scanning_image_template
    - name: registry
      value:
        ca_cert_data: ""
        repository: tap/supply-chain
        server: harbor.home.tanzu.rocks
    templateRef:
      kind: ClusterImageTemplate
      name: image-scanner-template
  - images:
    - name: image
      resource: image-scanner
    name: config-provider
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      options:
      - name: config-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: web
      - name: server-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: server
      - name: worker-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: worker
  - configs:
    - name: app_def
      resource: app-config
    name: service-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: service-bindings
  - configs:
    - name: app_def
      resource: service-bindings
    name: api-descriptors
    templateRef:
      kind: ClusterConfigTemplate
      name: api-descriptors
  - configs:
    - name: config
      resource: api-descriptors
    name: config-writer
    params:
    - default: default
      name: serviceAccount
    - name: registry
      value:
        ca_cert_data: ""
        repository: tap/supply-chain
        server: harbor.home.tanzu.rocks
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  - name: deliverable
    params:
    - name: registry
      value:
        ca_cert_data: ""
        repository: tap/supply-chain
        server: harbor.home.tanzu.rocks
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  selector:
    apps.tanzu.vmware.com/has-tests: "true"
  selectorMatchExpressions:
  - key: apps.tanzu.vmware.com/workload-type
    operator: In
    values:
    - web
    - server
    - worker
  - key: supplychain
    operator: In
    values:
    - full
    