
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: surfers-root
  #namespace: default
  description: Overall organisation parent group
spec:
  type: root
  profile:
    displayName: Surfer Top Level Group
  children: [surfers-crew]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: surfers-crew
  namespace: alpha
  description: Team focused on the Surfer system
spec:
  type: team
  profile:
    displayName: Surfer Crew
  parent: surfers-org
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: surfer-a
  namespace: alpha
spec:
  profile:
    displayName: Surfer Dude A
  memberOf: [surfers-crew]

---
