
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: surfersapi
  namespace: alpha
  description: API Gateway for SurfersLookout application to external systems
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=surferslookout,component=backend'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:surfers-crew
  system: surfers-system
  providesApis:
    - alpha/surfersapi

--- 

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: surfersapi
  namespace: alpha
  description: API Defintiion for backend
spec:
  type: openapi
  lifecycle: experimental

  owner: group:surfers-crew
  system: surfers-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: SurfersLookout API
      description: "Surferslookout forecast api"
    servers:
      - url: https://surfersapi.alpha.apps.tap1.home.tanzu.rocks/api/v1/api-docs
