
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: surfersapi
  namespace: alpha
  description: API Gateway for SurfersLookout application to external systems
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=surferslookout,component=backend'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:surfers-crew
  system: surfers-system
  providesApis:
    - surfersapi.alpha.tap1.home.tanzu.rocks
